feat: adding custom label handling for inputs
evervault/evervault-js pull request #50
Opened 2023-02-08 13:27 UTC by DeirdreCleary

# Why
The user should be able to set the labels they wish to use in their iframe, in particular as it will allow localization

# How
Passing all config fields from Inputs initialization to iFrame

2023-02-08 16:48 UTC, jeremywagemans requested changes
Just added a small comment there!

2023-02-08 16:50 UTC, DeirdreCleary commented on lib/v2/core/inputs.js
> +        setLabels: (labels) =>
Good catch! Updated

2023-02-08 17:51 UTC, jeremywagemans approved these changes
Great work on this one!

2023-02-09 09:49 UTC, merged

2023-02-09 09:50 UTC, DeirdreCleary commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/evervault-browser-sdk/v/2.2.0)
- [GitHub release](https://github.com/evervault/evervault-js/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: