feat: allow supplying the public key
evervault/evervault-js pull request #60
Opened 2023-03-13 13:34 UTC by DeirdreCleary

# Why
Customer request to support supplying the public key rather than calling out to the API for it.

# How
Allowed an additional param in the supplied config object to specify the `publicKey`. If present the call to the keys.evervault.com endpoint does not take place

2023-03-13 13:43 UTC, boilsquid requested changes

2023-03-13 13:43 UTC, boilsquid commented on lib/v1/index.js
> +    if (customConfig.publicKey) {
Can we add this as a test case please!

2023-03-13 17:22 UTC, DeirdreCleary commented on lib/v1/index.js
> +    if (customConfig.publicKey) {
Done ✅

2023-03-14 10:09 UTC, DogPawHat approved these changes

2023-03-14 14:02 UTC, closed without merging